/*
 * Copyright 2018 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __RTE_DEVICE_H
#define __RTE_DEVICE_H

/* Driver name mapping. */
#define RTE_USART1         1
#define RTE_USART1_DMA_EN  1
#define RTE_USART2         0
#define RTE_USART2_DMA_EN  0
#define RTE_USART3         0
#define RTE_USART3_DMA_EN  0
#define RTE_USART4         0
#define RTE_USART4_DMA_EN  0
#define RTE_USART5         0
#define RTE_USART5_DMA_EN  0
#define RTE_USART6         0
#define RTE_USART6_DMA_EN  0
#define RTE_USART7         0
#define RTE_USART7_DMA_EN  0
#define RTE_USART8         0
#define RTE_USART8_DMA_EN  0
#define RTE_USART9         0
#define RTE_USART9_DMA_EN  0
#define RTE_USART10        0
#define RTE_USART10_DMA_EN 0
#define RTE_USART11        0
#define RTE_USART11_DMA_EN 0
#define RTE_USART12        0
#define RTE_USART12_DMA_EN 0

/* UART configuration. */
#define RTE_USART1_DMA_TX_CH       0
#define RTE_USART1_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART1Tx
#if __CORTEX_M == 7
#define RTE_USART1_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART1_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART1_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART1_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART1_DMA_RX_CH       1
#define RTE_USART1_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART1Rx
#if __CORTEX_M == 7
#define RTE_USART1_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART1_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART1_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART1_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART2_DMA_TX_CH       2
#define RTE_USART2_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART2Tx
#if __CORTEX_M == 7
#define RTE_USART2_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART2_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART2_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART2_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART2_DMA_RX_CH       3
#define RTE_USART2_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART2Rx
#if __CORTEX_M == 7
#define RTE_USART2_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART2_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART2_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART2_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART3_DMA_TX_CH       4
#define RTE_USART3_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART3Tx
#if __CORTEX_M == 7
#define RTE_USART3_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART3_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART3_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART3_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART3_DMA_RX_CH       5
#define RTE_USART3_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART3Rx
#if __CORTEX_M == 7
#define RTE_USART3_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART3_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART3_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART3_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART4_DMA_TX_CH       6
#define RTE_USART4_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART4Tx
#if __CORTEX_M == 7
#define RTE_USART4_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART4_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART4_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART4_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART4_DMA_RX_CH       7
#define RTE_USART4_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART4Rx
#if __CORTEX_M == 7
#define RTE_USART4_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART4_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART4_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART4_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART5_DMA_TX_CH       8
#define RTE_USART5_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART5Tx
#if __CORTEX_M == 7
#define RTE_USART5_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART5_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART5_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART5_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART5_DMA_RX_CH       9
#define RTE_USART5_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART5Rx
#if __CORTEX_M == 7
#define RTE_USART5_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART5_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART5_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART5_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART6_DMA_TX_CH       10
#define RTE_USART6_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART6Tx
#if __CORTEX_M == 7
#define RTE_USART6_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART6_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART6_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART6_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART6_DMA_RX_CH       11
#define RTE_USART6_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART6Rx
#if __CORTEX_M == 7
#define RTE_USART6_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART6_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART6_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART6_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART7_DMA_TX_CH       12
#define RTE_USART7_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART7Tx
#if __CORTEX_M == 7
#define RTE_USART7_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART7_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART7_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART7_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART7_DMA_RX_CH       13
#define RTE_USART7_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART7Rx
#if __CORTEX_M == 7
#define RTE_USART7_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART7_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART7_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART7_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART8_DMA_TX_CH       14
#define RTE_USART8_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART8Tx
#if __CORTEX_M == 7
#define RTE_USART8_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART8_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART8_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART8_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART8_DMA_RX_CH       15
#define RTE_USART8_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART8Rx
#if __CORTEX_M == 7
#define RTE_USART8_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART8_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART8_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART8_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART9_DMA_TX_CH       16
#define RTE_USART9_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART9Tx
#if __CORTEX_M == 7
#define RTE_USART9_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART9_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART9_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART9_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART9_DMA_RX_CH       17
#define RTE_USART9_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART9Rx
#if __CORTEX_M == 7
#define RTE_USART9_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART9_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART9_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART9_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART10_DMA_TX_CH       18
#define RTE_USART10_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART10Tx
#if __CORTEX_M == 7
#define RTE_USART10_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART10_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART10_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART10_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART10_DMA_RX_CH       19
#define RTE_USART10_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART10Rx
#if __CORTEX_M == 7
#define RTE_USART10_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART10_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART10_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART10_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART11_DMA_TX_CH       20
#define RTE_USART11_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART11Tx
#if __CORTEX_M == 7
#define RTE_USART11_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART11_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART11_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART11_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART11_DMA_RX_CH       21
#define RTE_USART11_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART11Rx
#if __CORTEX_M == 7
#define RTE_USART11_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART11_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART11_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART11_DMA_RX_DMA_BASE    DMA1
#endif

#define RTE_USART12_DMA_TX_CH       22
#define RTE_USART12_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART12Tx
#if __CORTEX_M == 7
#define RTE_USART12_DMA_TX_DMAMUX_BASE DMAMUX0
#define RTE_USART12_DMA_TX_DMA_BASE    DMA0
#else
#define RTE_USART12_DMA_TX_DMAMUX_BASE DMAMUX1
#define RTE_USART12_DMA_TX_DMA_BASE    DMA1
#endif
#define RTE_USART12_DMA_RX_CH       23
#define RTE_USART12_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART12Rx
#if __CORTEX_M == 7
#define RTE_USART12_DMA_RX_DMAMUX_BASE DMAMUX0
#define RTE_USART12_DMA_RX_DMA_BASE    DMA0
#else
#define RTE_USART12_DMA_RX_DMAMUX_BASE DMAMUX1
#define RTE_USART12_DMA_RX_DMA_BASE    DMA1
#endif

#endif /* __RTE_DEVICE_H */
